import { db } from "@/db";import { arenaOwners,arenaDevices,webauthnCredentials,authenticatedSessions,securityEvents,deviceCapabilityGrants } from "@/db/schema";import { eq } from "drizzle-orm";import { assertLocalBootstrapEnabled } from "./identityConfig";import { hashSessionToken,issueSessionToken } from "./authorization";
const safe=(v:Record<string,unknown>)=>JSON.stringify(v);
export async function bootstrapOwnerDevice(input:{ownerName:string;deviceName:string;deviceType:string;credentialId:string;credentialPublicKey:string;nodePublicKey?:string},database:typeof db=db,env:NodeJS.ProcessEnv=process.env){assertLocalBootstrapEnabled(env);return database.transaction(async tx=>{if((await tx.select().from(arenaOwners).limit(1)).length)throw new Error("OWNER_ALREADY_EXISTS");const [owner]=await tx.insert(arenaOwners).values({displayName:input.ownerName}).returning();await tx.insert(securityEvents).values({ownerId:owner.id,type:"owner_created",outcome:"success"});const [device]=await tx.insert(arenaDevices).values({ownerId:owner.id,displayName:input.deviceName,deviceType:input.deviceType,enrollmentProvenance:"local_bootstrap",nodePublicKey:input.nodePublicKey}).returning();await tx.insert(webauthnCredentials).values({id:input.credentialId,ownerId:owner.id,deviceId:device.id,publicKey:input.credentialPublicKey});await tx.insert(securityEvents).values([{ownerId:owner.id,deviceId:device.id,type:"device_enrolled",outcome:"success",metadata:safe({provenance:"local_bootstrap"})},{ownerId:owner.id,deviceId:device.id,type:"credential_registered",outcome:"success",metadata:safe({credentialId:input.credentialId})}]);return{owner,device}})}
export async function createAuthenticatedSession(input:{ownerId:string;deviceId:string;credentialId:string;fresh:boolean;verifiedUserPresence:true;ttlMs?:number},database:typeof db=db){if(input.verifiedUserPresence!==true)throw new Error("VERIFIED_AUTHENTICATION_REQUIRED");const token=issueSessionToken(),now=new Date();const [session]=await database.insert(authenticatedSessions).values({tokenHash:hashSessionToken(token),ownerId:input.ownerId,deviceId:input.deviceId,credentialId:input.credentialId,freshVerifiedAt:input.fresh?now:null,expiresAt:new Date(now.getTime()+(input.ttlMs??8*60*60_000))}).returning();await database.insert(securityEvents).values({ownerId:input.ownerId,deviceId:input.deviceId,authenticatedSessionId:session.id,type:"session_created",outcome:"success"});return{token,session}}
export async function revokeSession(id:string,database:typeof db=db){const [s]=await database.update(authenticatedSessions).set({revokedAt:new Date()}).where(eq(authenticatedSessions.id,id)).returning();if(s)await database.insert(securityEvents).values({ownerId:s.ownerId,deviceId:s.deviceId,authenticatedSessionId:s.id,type:"session_revoked",outcome:"success"});return s}
export async function revokeDevice(id:string,reason:string,database:typeof db=db){return database.transaction(async tx=>{const [d]=await tx.update(arenaDevices).set({revokedAt:new Date(),revocationReason:reason,state:"revoked"}).where(eq(arenaDevices.id,id)).returning();if(d){await tx.update(authenticatedSessions).set({revokedAt:new Date()}).where(eq(authenticatedSessions.deviceId,id));await tx.insert(securityEvents).values({ownerId:d.ownerId,deviceId:d.id,type:"device_revoked",outcome:"success",metadata:safe({reason})})}return d})}
export async function completeFreshAuthentication(sessionId:string,database:typeof db=db){const [s]=await database.update(authenticatedSessions).set({freshVerifiedAt:new Date(),lastActivityAt:new Date()}).where(eq(authenticatedSessions.id,sessionId)).returning();if(s)await database.insert(securityEvents).values({ownerId:s.ownerId,deviceId:s.deviceId,authenticatedSessionId:s.id,type:"fresh_authentication_completed",outcome:"success"});return s}
export async function disableDevice(id:string,reason:string,database:typeof db=db){const [d]=await database.update(arenaDevices).set({state:"disabled",revocationReason:reason}).where(eq(arenaDevices.id,id)).returning();if(d)await database.insert(securityEvents).values({ownerId:d.ownerId,deviceId:d.id,type:"device_disabled",outcome:"success",metadata:safe({reason})});return d}
export async function revokeCapabilityGrant(id:string,database:typeof db=db){const [g]=await database.update(deviceCapabilityGrants).set({revokedAt:new Date()}).where(eq(deviceCapabilityGrants.id,id)).returning();if(g)await database.insert(securityEvents).values({ownerId:g.ownerId,deviceId:g.deviceId,type:"capability_grant_revoked",outcome:"success",metadata:safe({grantId:g.id,capability:g.capability})});return g}
export async function recordAuthenticationOutcome(input:{ownerId?:string;deviceId?:string;sessionId?:string;success:boolean;reason?:string},database:typeof db=db){return database.insert(securityEvents).values({ownerId:input.ownerId,deviceId:input.deviceId,authenticatedSessionId:input.sessionId,type:input.success?"device_authenticated":"authentication_failed",outcome:input.success?"success":"denied",metadata:safe(input.reason?{reason:input.reason}:{})}).returning()}
export async function grantDeviceCapability(input:{ownerId:string;deviceId:string;capability:string;resource:string;scope:string;effectClass?:string;createdByDeviceId:string},database:typeof db=db){const [g]=await database.insert(deviceCapabilityGrants).values(input).returning();await database.insert(securityEvents).values({ownerId:input.ownerId,deviceId:input.deviceId,type:"capability_grant_created",outcome:"success",metadata:safe({grantId:g.id,capability:g.capability,resource:g.resource})});return g}
