import {
  createLoopClips,
  sliceClipToBeatRange,
  type MusicalClipInput,
  type SliceResult,
} from "./clip-construction";

export type SectionBeatRange = {
  startBeatIndex: number;
  endBeatIndex: number;
};

export type SectionArrangementAction = "add" | "insert" | "loop";
export type SectionArrangementResult =
  | { ok: true; clips: MusicalClipInput[] }
  | {
    ok: false;
    reason:
      | "beat_grid_unavailable"
      | "beat_range_invalid"
      | "source_bounds_invalid"
      | "timeline_bounds_invalid"
      | "clip_capacity_exceeded"
      | "loop_repetitions_invalid";
  };

export const MAX_ARRANGEMENT_TIMELINE_MS = 86_400_000;

/**
 * Builds ordinary clips from an already-validated source section. Source-window
 * conversion and looping deliberately delegate to the existing Phase 9 helpers;
 * this adapter only applies a requested remix placement and capacity boundary.
 */
export function createSectionArrangementClips(
  template: MusicalClipInput,
  section: SectionBeatRange,
  beatGridMs: unknown,
  sourceDurationMs: number,
  timelineStartMs: number,
  tempoRatio: number,
  action: SectionArrangementAction,
  remainingTrackCapacity: number,
  repetitions = 1,
): SectionArrangementResult {
  if (!Number.isSafeInteger(timelineStartMs) || timelineStartMs < 0 || timelineStartMs > MAX_ARRANGEMENT_TIMELINE_MS)
    return { ok: false, reason: "timeline_bounds_invalid" };
  if (!Number.isInteger(remainingTrackCapacity) || remainingTrackCapacity < 1)
    return { ok: false, reason: "clip_capacity_exceeded" };
  const sliced: SliceResult = sliceClipToBeatRange(
    { ...template, timelineStartMs },
    beatGridMs,
    section.startBeatIndex,
    section.endBeatIndex,
    sourceDurationMs,
    tempoRatio,
  );
  if (!sliced.ok) return sliced;
  const base = sliced.clip;
  if (base.timelineStartMs + base.durationMs > MAX_ARRANGEMENT_TIMELINE_MS)
    return { ok: false, reason: "timeline_bounds_invalid" };
  if (action !== "loop") return { ok: true, clips: [base] };

  // A section loop consists of the placed source range plus independent repeats
  // generated by the pre-existing Phase 9 loop construction helper.
  if (!Number.isInteger(repetitions) || repetitions < 1 || repetitions > 64)
    return { ok: false, reason: "loop_repetitions_invalid" };
  if (repetitions + 1 > remainingTrackCapacity)
    return { ok: false, reason: "clip_capacity_exceeded" };
  const repeats = createLoopClips(base, repetitions, repetitions);
  if (!repeats) return { ok: false, reason: "loop_repetitions_invalid" };
  const clips = [base, ...repeats];
  if (clips.some((clip) => clip.timelineStartMs + clip.durationMs > MAX_ARRANGEMENT_TIMELINE_MS))
    return { ok: false, reason: "timeline_bounds_invalid" };
  return { ok: true, clips };
}

/** Current source/section provenance must agree before a section can drive a clip. */
export function sectionActionProvenanceReason(input: {
  sourceChecksumSha256: string;
  sectionChecksumSha256: string;
  sourceAnalysisId: string;
  sectionSourceAnalysisId: string;
  sectionAnalysisStatus: string;
  sectionAnalysisEngine: string;
  sectionAnalysisEngineVersion: string;
  sectionEngine: string;
  sectionEngineVersion: string;
}): "section_action_unavailable" | null {
  if (
    input.sectionAnalysisStatus !== "complete"
    || input.sourceChecksumSha256 !== input.sectionChecksumSha256
    || input.sourceAnalysisId !== input.sectionSourceAnalysisId
    || input.sectionAnalysisEngine !== input.sectionEngine
    || input.sectionAnalysisEngineVersion !== input.sectionEngineVersion
  ) return "section_action_unavailable";
  return null;
}
