/**
 * Typecheck with self-healing: a stale or interrupted `.next/dev/types`
 * (written by `next dev`) must never fail CI typecheck — those artifacts are
 * regenerated by the dev server on its next run, and a corrupted
 * validator.ts there breaks `tsc --noEmit` with unrelated syntax errors.
 *
 * We remove the directory (force, no error if absent) and run the project's
 * TypeScript compiler directly. Generated route types under `.next/types`
 * (from `next typegen` / `next build`) are still type-checked normally.
 */
import { rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
rmSync(path.join(root, ".next/dev/types"), { recursive: true, force: true });

const tsc = path.join(root, "node_modules", "typescript", "bin", "tsc");
const result = spawnSync(process.execPath, [tsc, "--noEmit", "--project", path.join(root, "tsconfig.json")], {
  stdio: "inherit",
  cwd: root,
});
process.exit(result.status ?? 1);
